### ISSUE TITLE
page.evaluate: DOMException: Failed to execute 'querySelector' on 'Document': '#40212789-4c76-413f-9054-05da2f0b4168' is not a valid selector.

### ISSUE THREAD

**Issue by thomasfischer-his** [A11yWatch/pagemind#58]
Using a setup similar as described in https://github.com/a11ywatch/a11ywatch/issues/65, I encounter an exception when scanning https://www.uniarts.se using runner 'axe'. The exception is not raised for other runners like 'htmlcs' or other webpages (as far as I can tell).

The scan is run using the latest [Docker container 'a11ywatch'](https://hub.docker.com/r/a11ywatch/a11ywatch). The container is launched via Podman as follows:

```bash
podman run --rm --interactive --add-host chrome:127.0.0.2 -p 3280:3280/tcp -p 50050:50050/tcp -p 50051:50051/tcp -p 50052:50052/tcp -p 50053:50053/tcp -p 50054:50054/tcp -p 9222:9222/tcp docker.io/a11ywatch/a11ywatch
```
Then, a scan is triggered by the following `curl` invocation:

```bash
curl --max-time 30 --location --request POST http://localhost:3280/api/scan -H 'Accept-Charset: utf-8' --header 'Content-Type: application/json' --data-raw '{ "url": "https://www.uniarts.se", "runners": ["axe"] }'
```

In the terminal where the container was started (not where curl is running), the following output is generated after the start of curl:

```
page.evaluate: DOMException: Failed to execute 'querySelector' on 'Document': '#40212789-4c76-413f-9054-05da2f0b4168' is not a valid selector.
    at eval (eval at evaluate (:208:30), <anonymous>:2:24)
    at UtilityScript.evaluate (<anonymous>:210:17)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
    at /usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/grab-alt.js:67:37
    at step (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/grab-alt.js:33:23)
    at Object.next (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/grab-alt.js:14:53)
    at /usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/grab-alt.js:8:71
    at __awaiter (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/grab-alt.js:4:12)
    at getAltImage (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/grab-alt.js:55:12)
    at /usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:76:75
    at step (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:33:23)
    at Object.next (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:14:53)
    at /usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:8:71
    at __awaiter (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:4:12)
    at /usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:70:101
    at /usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:70:68
    at step (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:33:23)
    at Object.next (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:14:53)
    at fulfilled (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:5:58) {
  name: 'Error'
}
page.evaluate: DOMException: Failed to execute 'querySelector' on 'Document': '#028181f4-9b25-4f3c-8ae1-8bc011cab1c0' is not a valid selector.
    at eval (eval at evaluate (:208:30), <anonymous>:2:24)
    at UtilityScript.evaluate (<anonymous>:210:17)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
    at /usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/grab-alt.js:67:37
    at step (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/grab-alt.js:33:23)
    at Object.next (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/grab-alt.js:14:53)
    at /usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/grab-alt.js:8:71
    at __awaiter (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/grab-alt.js:4:12)
    at getAltImage (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/grab-alt.js:55:12)
    at /usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:76:75
    at step (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:33:23)
    at Object.next (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:14:53)
    at /usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:8:71
    at __awaiter (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:4:12)
    at /usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:70:101
    at /usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:70:68
    at step (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:33:23)
    at Object.next (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:14:53)
    at fulfilled (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:5:58) {
  name: 'Error'
}
page.evaluate: DOMException: Failed to execute 'querySelector' on 'Document': '#2c6e39ca-260f-4f02-8712-5732ccfd2698' is not a valid selector.
    at eval (eval at evaluate (:208:30), <anonymous>:2:24)
    at UtilityScript.evaluate (<anonymous>:210:17)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
    at /usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/grab-alt.js:67:37
    at step (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/grab-alt.js:33:23)
    at Object.next (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/grab-alt.js:14:53)
    at /usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/grab-alt.js:8:71
    at __awaiter (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/grab-alt.js:4:12)
    at getAltImage (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/grab-alt.js:55:12)
    at /usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:76:75
    at step (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:33:23)
    at Object.next (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:14:53)
    at /usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:8:71
    at __awaiter (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:4:12)
    at /usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:70:101
    at /usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:70:68
    at step (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:33:23)
    at Object.next (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:14:53)
    at fulfilled (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:5:58) {
  name: 'Error'
}
page.evaluate: DOMException: Failed to execute 'querySelector' on 'Document': '#789700b2-41c3-482d-b778-c98563306d90' is not a valid selector.
    at eval (eval at evaluate (:208:30), <anonymous>:2:24)
    at UtilityScript.evaluate (<anonymous>:210:17)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
    at /usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/grab-alt.js:67:37
    at step (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/grab-alt.js:33:23)
    at Object.next (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/grab-alt.js:14:53)
    at /usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/grab-alt.js:8:71
    at __awaiter (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/grab-alt.js:4:12)
    at getAltImage (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/grab-alt.js:55:12)
    at /usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:76:75
    at step (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:33:23)
    at Object.next (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:14:53)
    at /usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:8:71
    at __awaiter (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:4:12)
    at /usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:70:101
    at /usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:70:68
    at step (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:33:23)
    at Object.next (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:14:53)
    at fulfilled (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:5:58) {
  name: 'Error'
}
page.evaluate: DOMException: Failed to execute 'querySelector' on 'Document': '#0f5caa8f-5936-4a82-9303-8d0dc918811d' is not a valid selector.
    at eval (eval at evaluate (:208:30), <anonymous>:2:24)
    at UtilityScript.evaluate (<anonymous>:210:17)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
    at /usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/grab-alt.js:67:37
    at step (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/grab-alt.js:33:23)
    at Object.next (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/grab-alt.js:14:53)
    at /usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/grab-alt.js:8:71
    at __awaiter (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/grab-alt.js:4:12)
    at getAltImage (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/grab-alt.js:55:12)
    at /usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:76:75
    at step (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:33:23)
    at Object.next (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:14:53)
    at /usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:8:71
    at __awaiter (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:4:12)
    at /usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:70:101
    at /usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:70:68
    at step (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:33:23)
    at Object.next (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:14:53)
    at fulfilled (/usr/src/app/node_modules/@a11ywatch/pagemind/core/lib/puppet/page/page-meta.js:5:58) {
  name: 'Error'
}
(node:40) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:40) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
```

Curl, having a 30 seconds timeout, provides the following out:

```
curl: (28) Operation timed out after 30001 milliseconds with 0 bytes received
```

Running a Bash instance inside the container, the following information got collected from `npm list | grep  -iE 'axe.?core|html.?code.?sniffer|html.?cs|a11y|kayle'`:

```
+-- @a11ywatch/client@0.0.5 extraneous
+-- @a11ywatch/core@0.8.15 extraneous
+-- @a11ywatch/crawler@0.8.12 extraneous
+-- @a11ywatch/mav@0.7.27 extraneous
+-- @a11ywatch/pagemind@0.9.54 extraneous
+-- @a11ywatch/protos@0.4.7 extraneous
+-- @a11ywatch/website-source-builder@0.1.14 extraneous
+-- axe-core@4.4.1 extraneous
+-- fast_axecore@4.6.31 extraneous
+-- fast_htmlcs@0.0.66 extraneous
+-- kayle_innate@0.0.22 extraneous
+-- kayle@0.7.12 extraneous
```

**Comment by j-mendez** [comment]
Hi, @thomasfischer-his the error is correct, the query selector is invalid so the element will not be able to be found. We could add a regex validation to prevent the timeout exceeding. Going to push this minor change up, you can remove the AI feature with an env variable to prevent the figuring out alt images too.

**Comment by j-mendez** [comment]
Fixed https://github.com/a11ywatch/pagemind/commit/39b283d823eab80ca1762e0beb1fde155c2ab7cb the single image for pagemind is deployed, the suite image via a11ywatch should be deployed in the next hour. You can upgrade the instances with the CLI to get the newest images. Thanks for the issue!
